### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by rdebath** [simon-i1-h/mushroom#1]
`{int ch; if ((ch=getchar()) == EOF) break; m[p]=ch;}`

Okay, that's a pretty good idea ... but what's supposed to happen if the `,` command isn't in a loop?

**Comment by shimon1024** [comment]
@rdebath The behavior when EOF occurs using the `,` command outside the loop is undefined. But I think that there is nothing to worry.

(meta: Using google translator.)

**Comment by shimon1024** [comment]
@rdebath ping

May I close the issue?

**Comment by rdebath** [comment]
Of course you may, you have answered the question and given a reasonable response, but most importantly this is your repository.
